### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dolar2006** [nt4f04uNd/nt4f04unds_widgets#2]
![photo_2021-07-09 12 04 43](https://user-images.githubusercontent.com/5747755/125053536-e58b2e80-e0ad-11eb-8c29-d83d25195794.jpeg)

**Comment by nt4f04uNd** [comment]
You need to switch to any other Flutter channel except for stable, since this has not landed there yet.

**Comment by dolar2006** [comment]
![image](https://user-images.githubusercontent.com/5747755/125066701-f93d9180-e0bb-11eb-8ed7-282308d782c1.png)
this did not solve the problem
flutter: 2.4.0-1.0.pre.149

**Comment by nt4f04uNd** [comment]
This did solve the problem, you are hitting some other problem unrelated to this package
