### ISSUE TITLE
Flutter version dependencies are not specified, because of this it is not possible to run the package

### ISSUE THREAD

**Issue by dolar2006** [nt4f04uNd/nt4f04unds_widgets#4]
NOT WORK. Flutter version dependencies are not specified, because of this it is not possible to run the package.
You need to explicitly specify dependencies
Example:
![image](https://user-images.githubusercontent.com/5747755/125467912-d15d3c4d-ac4e-4c7e-899e-47c64e077c80.png)

**Comment by nt4f04uNd** [comment]
I agree this should be added

Though `environment` only specifies the restriction on the version of the SDK, if you have an SDK version that doesn't fit this restriction you will not be able to run a project

**Comment by dolar2006** [comment]
When can you add?
