### ISSUE TITLE
What for widgets through methods builds?

### ISSUE THREAD

**Issue by dolar2006** [nt4f04uNd/nt4f04unds_widgets#7]
What for widgets through methods builds?
![image](https://user-images.githubusercontent.com/5747755/125468788-adae6aa1-e070-4af3-8d68-c0b9239ef3a5.png)

**Comment by nt4f04uNd** [comment]
For building a button. FYI This widget is old and staged for removal, the same look can be easily achieved with new buttons https://flutter.dev/docs/release/breaking-changes/buttons
