### ISSUE TITLE
Why is the widget implemented this way? So that if the topic changes - where she participates - is not automatically replaced with a new one?

### ISSUE THREAD

**Issue by dolar2006** [nt4f04uNd/nt4f04unds_widgets#8]
Why is the widget implemented this way? So that if the topic changes - where she participates - is not automatically replaced with a new one?
![image](https://user-images.githubusercontent.com/5747755/125469202-5b362180-ceae-4655-8ff6-846399f63a49.png)

**Comment by nt4f04uNd** [comment]
Because I avoid using context dependencies due to personal preferences related to performance harm
